language: rust
rust: nightly
services: docker
matrix:
  fast_finish: true
  include:
  - env: RUSTFMT
    before_script:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt -- --write-mode=diff
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: stable
  - env: TARGET=x86_64-unknown-linux-gnu
  - env: TARGET=i686-unknown-linux-gnu
  - env: TARGET=i686-apple-darwin
    os: osx
    osx_image: xcode9.2
  - env: TARGET=x86_64-apple-darwin
    os: osx
    osx_image: xcode9.2

script: ci/run.sh

notifications:
  email:
    on_success: never
